# -*- coding: utf-8 -*-
"""Story_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXBOzzZ8Ul7-CpZlSu9cwH2R01_cI9dn
"""

!pip install  -q -U google-genai

from google  import genai
from google.genai import types
from google.colab import userdata


client = genai.Client(api_key=userdata.get('GEMINI_API_KEYS'))

for m in client.models.list():
  print(m.name)

repsonse = client.models.generate_content(
    model = 'gemini-3.5-flash-lite',
    contents ='tell me one line of joke about developers.', #user prompts
    config=types.GenerateContentConfig(
        system_instruction='you are a helpful assistant',
        temperature=0.5,
        max_output_tokens=200,
        thinking_config=types.ThinkingConfig(thinking_level='low')
        )
)


print("text generated by AI:",repsonse.text)

print()
u = repsonse.usage_metadata

print("usgae", repsonse.usage_metadata)



print("")

print("prompt_token_count", u.prompt_token_count)
print('candidates_token_count', u.candidates_token_count)

print('total_token_count', u.total_token_count)
print()
print()

#build story generator and take inputs from users (topic, genre take from users)

from google import genai
from google.genai import types
from google.colab import userdata

# Create Gemini client
client = genai.Client(api_key=userdata.get('GEMINI_API_KEYS'))

MODEL = 'gemini-3.5-flash-lite'


def generate_story(topic, genre, length_word=200):
    prompt = f"""
    Write a creative story based on the following details:

    Topic: {topic}
    Genre: {genre}
    Length: approximately {length_word} words

    Make the story interesting, engaging, and easy to understand.
    Give the story a suitable title.
    """

    response = client.models.generate_content(
        model=MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            system_instruction="You are a creative and helpful story writer.",
            temperature=0.8,
            max_output_tokens=500
        )
    )

    return response.text


# Take inputs from the user
topic = input("Enter the story topic: ")
genre = input("Enter the story genre: ")

# Generate the story
story = generate_story(topic, genre)

# Display the story
print("\n===== GENERATED STORY =====\n")
print(story)